[[bookmarks]]
path = "https://github.com/termide/termide"
created_at = "2026-04-03T20:00:01.321380058Z"
description = "Github repository"

[[bookmarks]]
path = "https://termide.github.io/"
created_at = "2026-04-03T20:02:07.049219431Z"
description = "Web site"
